###############################################################################
# Makefile FAME example
#
# Oscar Orallo Pelaez
# Date: 03-02-2006
###############################################################################

TARGET = example
OBJS = main.o
CFLAGS = -O2 -I../include
LDFLAGS = -L../x86/linux
CC = gcc
STRIP = strip

$(TARGET) : $(OBJS)
			$(CC) $(CFLAGS) $(LDFLAGS) $(OBJS) -o $(TARGET) -lfame
			$(STRIP) $(TARGET)

all: $(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)

